### ISSUE TITLE
NeoForge 26.3 broken

### ISSUE THREAD

**Issue by NamelessJu** [rotgruengelb/stonecutter-mod-template#31]
I keep getting the following error whenever I try to runActiveClient or build on 26.3-neoforge:

```cmd
*** Started working on recompile
 106 items on the compile classpath
 0 items on the sourcepath
 Compiling 7301 source files
 ERROR Line: 44, contents() in <anonymous net.minecraft.core.HolderSet$1> cannot override contents() in net.minecraft.core.HolderSet.Named
  attempting to assign weaker access privileges; was public in /net/minecraft/core/HolderSet.java
Total runtime: 23.50s

net.neoforged.neoform.runtime.graph.NodeExecutionException: Node action for recompile failed
	at net.neoforged.neoform.runtime.engine.NeoFormEngine.runNode(NeoFormEngine.java:612)
	at net.neoforged.neoform.runtime.engine.NeoFormEngine.lambda$getWaitCondition$5(NeoFormEngine.java:558)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1825)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:291)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:460)
Caused by: java.io.IOException: Compilation failed
	at net.neoforged.neoform.runtime.actions.RecompileSourcesActionWithJDK.run(RecompileSourcesActionWithJDK.java:77)
	at net.neoforged.neoform.runtime.engine.NeoFormEngine.runNode(NeoFormEngine.java:601)
	... 4 more
Caused by: java.io.IOException: Compilation failed


> Task :26.3-neoforge:createMinecraftArtifacts FAILED
```

NeoForge 26.2 still works fine for me, and Fabric 26.3 also works without issues.  
I tried the NeoForge 26.3 template from their official website and it works using the same and latest NeoForge version (26.3.0.16-beta), while this stonecutter setup seems to have issues.

idk what causes this because looking at the Fabric 26.3 code HolderSet.Named's contents() method is supposed to be protected, so idk why NeoForge claims it's public (some inbuilt access widener I suppose?) and why it's then still being overridden with the original access modifier in HolderSet.emptyNamed()'s anonymous class...

**Comment by NamelessJu** [comment]
ok I figured it out, updating moddevgradle fixes it!
